function ExperimentOutput = SSDBEvaluate_PixelwiseObjRec(ExperimentStructure, EmpTestData);
%function ExperimentOutput = SSDBEvaluate_PixelwiseObjRec(ExperimentStructure, EmpTestData);
%
% Returns a structure containing common statistics regarding performance on the pixelwise
% object detection task.  Input is the ExperimentStructure output from 
% SSDBExperiment_PixelwiseObjRec, and the EmpTestData generated by your object detection mechanism
% EmpTestData should be the same size and shape as ExperimentStructure.TestValue, the baseline
% truth.

TrueValues = ExperimentStructure.TestValues;
if(any(size(EmpTestData) ~= TrueValues))
  error('Emperical and True data structures do not match size\n');
end

nObjects = size(TrueValues,1)
for i = 1:nObjects
  objname = ExperimentStructure.options.caObjectsToInclude{i};
  ExperimentOutput.(objname).ROC = ROCetc(EmpTestData(i,:), ExperimentStructure(i,:),1);
end
  
